[package]
name = "signer"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
near-sdk.workspace = true
lib = { path = "../../lib", features = ["debug"] }

[lib]
crate-type = ["cdylib"]
