[package]
authors = ["Jacob Lindahl <jacob.lindahl@near.org>"]
name = "near-multichain-gas-station-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers-core = "2.0.13"
getrandom = { version = "0.2", features = [
    "custom",
] } # make this package happy for wasm target
hex = "0.4"
near-sdk.workspace = true
near-sdk-contract-tools = "2.1"
schemars = "0.8.16"
thiserror = "1"

[features]
default = []

# enables functions only for testing purposes
# NOT SAFE FOR PRODUCTION USE
debug = []

[target.'cfg(not(target_family = "wasm"))'.dependencies]
sha2 = "0.10.8"

[dev-dependencies]
near-workspaces = { version = "0.10", features = ["unstable"] }
tokio = "1.28"

[lib]
crate-type = ["cdylib", "lib"]

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "z"
overflow-checks = true
panic = "abort"
strip = true

[workspace]
members = [".", "mock/*"]

[workspace.dependencies]
near-sdk = { version = "4.1.1", default-features = false, features = [
    "wee_alloc",
    "legacy",
    "abi",
] }
