[package]
authors = ["Jacob Lindahl <jacob.lindahl@near.org>"]
name = "near-multichain-xchain-relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2", default-features = false }
hex = "0.4"
near-sdk = { git = "https://github.com/near/near-sdk-rs.git", tag = "near-sdk-v5.0.0-alpha.1", default-features = false, features = [
    "wee_alloc",
    "legacy",
    "abi",
] }
near-sdk-contract-tools = "2"

# make this package happy for wasm target
getrandom = { version = "0.2", features = ["js"] }

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "z"
overflow-checks = true
panic = "abort"
