[workspace]
resolver = "2"
members = ["gas_station", "key_manager", "lib", "mock/*"]

[workspace.dependencies]
ethers-core = "2.0.13"
near-sdk = { version = "4.1.1", default-features = false, features = [
    "wee_alloc",
    "legacy",
    "abi",
] }
near-sdk-contract-tools = "2.1"
schemars = "0.8.16"
thiserror = "1"

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "z"
overflow-checks = true
panic = "abort"
strip = true
