[tasks.build]
workspace = false
clear = true
script = """
cargo build --package gas-station --target wasm32-unknown-unknown --release --no-default-features
"""

[tasks.build-debug]
workspace = false
script = """
cargo build --package gas-station --target wasm32-unknown-unknown --release --features=debug
"""

[tasks.test]
workspace = false
clear = true
script = """
mkdir -p target/near/{gas_station,oracle,signer}
cargo test
"""

[tasks.nextest]
workspace = false
clear = true
script = """
mkdir -p target/near/{gas_station,oracle,signer}
cargo nextest run
"""

[tasks.clear-contract]
workspace = false
script_runner = "@shell"
script = '''
ENTRIES=$(near contract view-storage canhazgas.testnet all as-json network-config testnet now)
JSON="{\"entries\": $ENTRIES}"
near contract call-function as-transaction canhazgas.testnet clear_storage json-args "$JSON" prepaid-gas '300.0 Tgas' attached-deposit '0 NEAR' sign-as
'''
